site_name: RSE-Software Entwicklungs Leitlinien
site_url: https://gi-ev.github.io/RSE-software-entwicklungs-leitlinien
theme:
  name: material
  features:
    - navigation.footer
    - navigation.top

copyright: '&copy; Software Guidelines workin group, CC0 1.0 deed'

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
      toc_depth: 3

# page tree
nav:
  - Home: index.md
  - Glossary: glossar.md
