site_name: RSE-Software Entwicklungs Leitlinien
site_url: https://luepges.github.io/RSE-software-entwicklungs-leitlinien
theme:
  name: material
  features:
#    - navigation.top
    - navigation.footer

copyright: '&copy; Software Guidelines workin group, CC0 1.0 deed'
    
markdown_extensions:
  - attr_list
    
# page tree
nav:
  - Home: index.md
  - Glossary: glossar.md
