name: Build and update gh pages
on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Build main site
        run: mkdocs build
      - name: Build example site
        run: mkdocs build --site-dir ../site/website_template
        working-directory: website_template
      - name: Deploy to gh-pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: oprypin/push-to-gh-pages@v3
        with:
          publish_dir: site